version: "3.8"

services:
  portfolio:
    container_name: portfolio-container
    image: portfolio-image

    build:
      context: .
      dockerfile: ./Dockerfile.prod


    volumes:
      - .:/portfolio

    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure

    platform: linux/amd64


