FROM  node:18-alpine AS build

WORKDIR /portfolio

COPY ./package.json .

COPY ./package-lock.json .

RUN npm install

COPY . .

RUN npm run build


# stage 2 - build the final image and copy the react build files
FROM nginx:1.23.3-alpine

COPY --from=build /portfolio/dist /var/www/html/

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/

COPY nginx/portfolio.conf /etc/nginx/conf.d/

EXPOSE 80

EXPOSE 443